#!/bin/sh

path=$(pwd)


# Home
ln -sf $path/.bash_profile $HOME/.bash_profile
ln -sf $path/.bashrc $HOME/.bashrc
ln -sf $path/.xinitrc $HOME/.xinitrc
ln -sf $path/.tmux.conf $HOME/.tmux.conf


# Config directory
[ ! -d $HOME/.config ] && mkdir $HOME/.config
[ -d $HOME/.config/mpd ] && rm -rf $HOME/.config/mpd
ln -sf $path/config/mpd $HOME/.config/mpd

[ -d $HOME/.config/mpDris2 ] && rm -rf $HOME/.config/mpDris2
ln -sf $path/config/mpDris2 $HOME/.config/mpDris2

[ -d $HOME/.config/mpv ] && rm -rf $HOME/.config/mpv
ln -sf $path/config/mpv $HOME/.config/mpv

[ ! -d $HOME/.config/nvim ] && mkdir $HOME/.config/nvim
# ln -sf $path/.config/nvim $HOME/.config/nvim
# ln -sf $path/.config/nvim $HOME/.config/nvim

[ ! -d $HOME/.config/ncmpcpp ] && mkdir $HOME/.config/ncmpcpp
ln -sf $path/.config/ncmpcpp $HOME/.config/ncmpcpp

[ ! -d $HOME/.config/picom ] && mkdir $HOME/.config/picom
ln -sf $path/.config/picom $HOME/.config/picom

[ -d $HOME/.config/sxhkd ] && rm -rf $HOME/.config/sxhkd
ln -sf $path/config/sxhkd $HOME/.config/sxhkd

[ -d $HOME/.config/sxiv ] && rm -rf $HOME/.config/sxiv
ln -sf $path/config/sxiv $HOME/.config/sxiv

[ -d $HOME/.config/zathura ] && rm -rf $HOME/.config/zathura
ln -sf $path/config/zathura $HOME/.config/zathura

ln -sf $path/config/mimeapps.list $HOME/.config/mimeapps.list
