require('plugins')
require('completion/cmp')
-- require('completion/lsp-install')
require('general')
require('bindings')
require('plugins/startify')
require('plugins/whichkey')
require('plugins/vimtex')
require('plugins/autopairs')
require('plugins/telescope')
require('plugins/colorizer')
require('plugins/lualine')
require('onedark').load()

